# Lines configured by zsh-newuser-install
HISTFILE=~/.config/zsh/histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob nomatch
unsetopt beep notify
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/steve/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# use dvorak for spelling correction
setopt dvorak

# use vi keys for info
alias info='info --vi-keys'

# set prompt
alias battery_charge="echo '['\$(acpi | grep -v 'rate information unavailable' | grep -o '[CDU]\|[[:digit:]]*%')'%]'"
prompt off
PROMPT='%1~ %# '
if [[ $(tty) = /dev/tty*(#qN) ]]
then
	RPROMPT="%(?..%?   )\$(echo '['\$(acpi | grep -v 'rate information unavailable' | grep -o '[CDU]\|[[:digit:]]*%')'%]')   \$(amixer get Master | grep -o '\[[[:digit:].-]*dB\] \[[[:lower:]]*\]')   %*"
fi
setopt prompt_subst

# keyboard layout aliases
alias aoeu='sudo loadkeys us'
alias asdf='sudo loadkeys /usr/local/share/kbd/keymaps/dvp.map'

# notify GPG agent of current TTY
#gpg-connect-agent updatestartuptty /bye > /dev/null
