# Lines configured by zsh-newuser-install
HISTFILE=~/.config/zsh/histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd beep extendedglob
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/steve/.config/zsh/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# use dvorak for spelling correction
setopt dvorak

# set aliases and prompt
source $HOME/.config/zsh/aliases
source $HOME/.config/zsh/prompt

# notify GPG agent of current TTY
gpg-connect-agent updatestartuptty /bye > /dev/null
