# Lines configured by zsh-newuser-install
HISTFILE=~/.config/zsh/histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob nomatch
unsetopt beep notify
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/steve/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# use dvorak for spelling correction
setopt dvorak

# use vi keys for info
alias info='info --vi-keys'

# set prompt
prompt off
PROMPT='%1~ %# '

# notify GPG agent of current TTY
#gpg-connect-agent updatestartuptty /bye > /dev/null
